[package]
name = "duat-sneak"
version = "0.1.1"
authors = ["AhoyISki"]
description = "A Duat plugin for finding character sequences, inspired by vim-sneak"
repository = "https://github.com/AhoyISki/duat-sneak"
license = "AGPL-3.0-or-later"
readme = "README.md"
keywords = ["editor", "text", "plugin", "duat"]
categories = ["command-line-utilities", "text-editors", "config"]
edition = "2024"

[dependencies]
duat-core = { version = "0.5.2", git = "https://github.com/AhoyISki/duat" }
